services:
  web:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      args:
        - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
        - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
        - AWS_REGION=${AWS_REGION}
        - S3_RAW_BUCKET=${S3_RAW_BUCKET}
        - S3_COMPRESSED_BUCKET=${S3_COMPRESSED_BUCKET}
        - S3_PREFIX=${S3_PREFIX}
        - MAX_UPLOAD_SIZE=${MAX_UPLOAD_SIZE}
        - MAX_TOTAL_UPLOAD=${MAX_TOTAL_UPLOAD}
        - LOG_DIRECTORY=${LOG_DIRECTORY}
    ports:
      - "8080:80"
    env_file:
      - .env
    volumes:
      - ./public:/var/www/html
      - ./docker/config:/var/www/config
      - ./src:/var/www/src
      - ./vendor:/var/www/vendor
      - ./logs:/var/www/logs
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
      - AWS_BUCKET_RAW=${S3_RAW_BUCKET}
      - AWS_BUCKET_COMPRESSED=${S3_COMPRESSED_BUCKET}
      - S3_RAW_BUCKET=${S3_RAW_BUCKET}
      - S3_COMPRESSED_BUCKET=${S3_COMPRESSED_BUCKET}
      - S3_PREFIX=${S3_PREFIX}
      - MAX_UPLOAD_SIZE=${MAX_UPLOAD_SIZE}
      - MAX_TOTAL_UPLOAD=${MAX_TOTAL_UPLOAD}
      - LOG_DIRECTORY=${LOG_DIRECTORY} 